Add files via upload
royJackman/No529 pull request #9
Opened 2017-11-12 23:13 UTC by joshualevine

search page format set up

2017-11-21 02:41 UTC, neal-merkl requested changes
Some layout changes

2017-11-21 02:41 UTC, anmerkl commented on HPEMobileApp/app/search/search-page.xml
> +                    <TextField class="page-search-field" text="{{ system_ID }}" hint="system name" col="1" />
`hint` is something you use for additional explanation of what a text field is for.
Having the hint be the same text as the Label defeats the whole point of it.
This should be an example of 'System Name' instead.

This applies to all hints on this page.

2017-11-21 02:41 UTC, anmerkl commented on HPEMobileApp/app/search/search-page.xml
> +                    <Label class="search-field-label" text="Location: Region:" col="0" />
This Label is a little confusing. Either split it up into two different Labels with better spacing or just pick one of the fields to use.

2017-11-21 02:41 UTC, anmerkl commented on HPEMobileApp/app/search/search-page.xml
> +                    <TextField class="page-search-field" text="{{ country }}" hint="" col="3" />
Put this on its own line and indent it instead of having it on one line. It gets cluttered on mobile screens.

2017-11-21 03:03 UTC, neal-merkl requested changes
the configuration folder should be inside the HPEMobileApp folder. move the folder and update all file names.

Also it doesn't look like the configuration page is reachable from anywhere?

Also you have code for the menu app drawer inside here, but it looks like that already exists in master. Please verify

2017-11-21 23:50 UTC, joshualevine commented
Accidentally pushed from old account. Deleted the old account but I can't figure out how to remove the commit. Probably doesn't matter. 
Also, I don't know what you are referring to by "configuration fold" and "configuration page". All I have done is edited the files in the "search" directory and the added the css file for it and added a new directory "search-results" and all the files in it.

2017-11-26 19:06 UTC, anmerkl commented
oh, I was reviewing two pull requests at the same time and put comments from the other PR into this one. Sorry, I'll re-review now.

2017-11-26 19:09 UTC, neal-merkl approved these changes
lgtm

2017-11-30 18:16 UTC, merged